12.3.2. Напишите программу, которая проверяет, равны ли два трёхмерных массива. Сначала сравните их размеры, и если они совпадают, сравните массивы по значениям.

In [11]:
a=[ [[1,2],[4,5]] , [[7,8],[0,9]] ]
b=[ [[9,9],[4,5]] , [[7,8],[0,9]] ]

elements=0

if len(a)==len(b):
    
    for i in range(len(a)):
        for j in range(len(a[i])):
            if a[i][j]==b[i][j]:
                elements+=1
    if elements==(i+1)*(j+1):
        print("arrays are equivalent!")
    if elements!=(i+1)*(j+1):
        print("arrays are not equivalent!")

arrays are not equivalent!


12.3.6. Напишите программу, которая симметрично отражает матрицу относительно её главной диагонали.

In [9]:
# пример из интернетов, 
a = [[1, 2, 3], [4, 5, 6]]
b = [[x[i] for x in a] for i in range(len(a[0]))]
print (b)


[[1, 4], [2, 5], [3, 6]]


In [20]:
array1=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
array2=[]
for i in range(0, len(array1[0]):
    array2.append([])
    for j in range(0, len(array1):
        array2[i].append(array1[j][i])
print(array2)

SyntaxError: invalid syntax (<ipython-input-20-06f94e97980a>, line 3)

In [17]:
# решение с использованием модуля Numpy
# pip inslall numpy

import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
a = a.transpose()
print(a)

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [ ]:

Задачки можете тут посмотреть:
https://acmp.ru/index.asp?main=tasks
там есть раздел "двумерные массивы", и дополнительно по сложности можно выбирать.